import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import {
  AboutBlockType,
  BannerContentType,
  MenuBlockType,
  MenuType,
  ServicesBlockType,
  ServicesType,
  TeamBlockType,
  TeamType,
} from "../types/type";
import Services from "../components/Services";
import AboutBlock from "../components/AboutBlock";
import MenuBlock from "../components/MenuBlock";
import TeamBlock from "../components/TeamBlock";

interface Props {
  bannerContent: BannerContentType;
  serviceBlockData: ServicesBlockType;
  servicesData: ServicesType[];
  aboutBlockData: AboutBlockType;
  menuBlockData: MenuBlockType;
  menuData: MenuType[];
  teamBlockData: TeamBlockType;
  teamData: TeamType[];
}

const Home: NextPage<Props> = ({
  bannerContent,
  serviceBlockData,
  servicesData,
  aboutBlockData,
  menuBlockData,
  menuData,
  teamBlockData,
  teamData,
}) => {
  return (
    <>
      <Head>
        <title>Restoran</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner {...bannerContent} />
      <Services
        serviceBlockData={serviceBlockData}
        servicesData={servicesData}
      />
      <AboutBlock {...aboutBlockData} />
      <MenuBlock menuBlockData={menuBlockData} menuData={menuData} />
      <TeamBlock teamBlockData={teamBlockData} teamData={teamData} />
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("http://localhost:5001/banner_content");
  const data: BannerContentType = await res.json();

  const serviceBlockRes = await fetch("http://localhost:5001/services_block");
  const serviceBlockData: ServicesBlockType = await serviceBlockRes.json();

  const servicesRes = await fetch("http://localhost:5001/services");
  const servicesData: ServicesType[] = await servicesRes.json();

  const aboutBlockRes = await fetch("http://localhost:5001/about_block");
  const aboutBlockData: AboutBlockType = await aboutBlockRes.json();

  const menuBlockRes = await fetch("http://localhost:5001/menu_block");
  const menuBlockData: MenuBlockType = await menuBlockRes.json();

  const menuRes = await fetch("http://localhost:5001/menu");
  const menuData: MenuType[] = await menuRes.json();

  const teamBlockRes = await fetch("http://localhost:5001/team_block");
  const teamBlockData: TeamBlockType = await teamBlockRes.json();

  const teamRes = await fetch("http://localhost:5001/team");
  const teamData: TeamType[] = await teamRes.json();

  return {
    props: {
      bannerContent: data,
      serviceBlockData,
      servicesData,
      aboutBlockData,
      menuBlockData,
      menuData,
      teamBlockData,
      teamData,
    },
  };
};
