import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import CategoryPicker from "../components/CategoryPicker";
import FeaturedBlogs from "../components/FeaturedBlogs";
import FeaturedProducts from "../components/FeaturedProducts";
import {
  BannerContentType,
  FeaturedBlogsType,
  FeaturedProductsType,
} from "../types/type";

interface Props {
  bannerContentData: BannerContentType;
  featuredProductsData: FeaturedProductsType[];
  featuredBlogsData: FeaturedBlogsType[];
}

const Home: NextPage<Props> = ({
  bannerContentData,
  featuredProductsData,
  featuredBlogsData,
}) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner {...bannerContentData} />

      <CategoryPicker />

      <FeaturedProducts featuredProductsData={featuredProductsData} />

      <FeaturedBlogs featuredBlogsData={featuredBlogsData} />
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const bannerContentRes = await fetch("http://localhost:5001/banner_content");
  const bannerContentData: BannerContentType = await bannerContentRes.json();

  const featuredProductsRes = await fetch(
    "http://localhost:5001/products/?_limit=4"
  );
  const featuredProductsData: FeaturedProductsType[] =
    await featuredProductsRes.json();

  const featuredBlogsRes = await fetch("http://localhost:5001/blogs/?_limit=3");
  const featuredBlogsData: FeaturedBlogsType[] = await featuredBlogsRes.json();

  return {
    props: {
      bannerContentData: bannerContentData,
      featuredProductsData: featuredProductsData,
      featuredBlogsData: featuredBlogsData,
    },
  };
};
