import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import Services from "../components/Services";
import Team from "../components/Team";
import { HomePageType, ServicesType, TeamType } from "../types/types";

export interface BannerContent {
  title: string;
  content: string;
}

export interface TitleBlock {
  title: string;
  preTitle: string;
}

export interface ServicesPageType {
  services_block: {
    preTitle: string;
    title: string;
  };
  team_block: {
    preTitle: string;
    title: string;
  };
}
interface HomeProps {
  bannerContent: BannerContent;
  dataServicesBlock: TitleBlock;
  dataTeamBlock: TitleBlock;
  dataServices: ServicesType[];
  dataTeam: TeamType[];
}
const Home: NextPage<HomeProps> = ({
  bannerContent,
  dataServicesBlock,
  dataTeamBlock,
  dataServices,
  dataTeam,
}) => {
  return (
    <>
      <Head>
        <title>Arhitektur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner title={bannerContent.title} content={bannerContent.content} />
      <Services dataServicesBlock={dataServicesBlock} services={dataServices} />
      <Team dataTeamBlock={dataTeamBlock} dataTeam={dataTeam} />
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const resData = await fetch("http://localhost:5001/homepage");
  const data: HomePageType = await resData.json();

  const resServicesPage = await fetch("http://localhost:5001/services_page");
  const dataServicesPage: ServicesPageType = await resServicesPage.json();

  const resServices = await fetch("http://localhost:5001/services");
  const dataServices: ServicesType[] = await resServices.json();

  const resTeam = await fetch("http://localhost:5001/team");
  const dataTeam: TeamType[] = await resTeam.json();
  return {
    props: {
      bannerContent: data.banner_content,
      dataTeamBlock: dataServicesPage.team_block,
      dataServicesBlock: dataServicesPage.services_block,
      dataServices,
      dataTeam,
    },
  };
};
