import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import PageTitle from "../../components/PageTitle";
import RelatedBlogs from "../../components/RelatedBlogs";
import { FeaturedBlogsType } from "../../types/type";
import ProductItem from "../../components/ProductItem";
import { useEffect, useState } from "react";

interface Props {
  product: FeaturedBlogsType;
  allFeaturedBlogsData: FeaturedBlogsType[];
}

const BlogDetail: NextPage<Props> = ({ product, allFeaturedBlogsData }) => {
  const [relatedBlogsData, setRelatedBlogsData] = useState<FeaturedBlogsType[]>(
    []
  );

  const fetchRelatedBlogs = () => {
    const MIN_RELATED_BLOGS = 3;

    let relatedBlogs = [];
    let sameIndexes = new Set();

    //  we are ensuring that the relatedBlogs won't be less than 3
    while (relatedBlogs.length < MIN_RELATED_BLOGS) {
      const randomNo = Math.floor(Math.random() * allFeaturedBlogsData.length);
      if (!sameIndexes.has(randomNo)) {
        sameIndexes.add(randomNo);
        relatedBlogs.push(allFeaturedBlogsData[randomNo]);
      }
    }

    // we are ensuring that the relaredBlogs won't be more than 3
    if (relatedBlogs.length > 3) {
      relatedBlogs = relatedBlogs.slice(0, 2);
    }

    return relatedBlogs;
  };

  useEffect(() => {
    const relatedBlogs = fetchRelatedBlogs();
    setRelatedBlogsData(relatedBlogs);
  }, []);

  return (
    <>
      <Head>
        <title>Store - title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title="Blog Detail" />

      <section className="bg0 p-t-52 p-b-20">
        <div className="container">
          <div className="row">
            <div className="col-md-8 col-lg-9 p-b-80">
              <div className="p-r-45 p-r-0-lg">
                <div className="wrap-pic-w how-pos5-parent">
                  <img src={product.img} alt="IMG-BLOG" />
                </div>

                <div className="p-t-32">
                  <span className="flex-w align-items-center flex-m stext-111 cl2 p-b-19">
                    <span className="flex-c-m mr-3 bor7 p-lr-15 trans-04">
                      {product.category}
                    </span>

                    <span>
                      <span className="cl4">By</span> {product.author}
                      <span className="cl12 m-l-4 m-r-6">|</span>
                    </span>

                    <span>date</span>
                  </span>

                  <h4 className="ltext-109 cl2 p-b-28">{product.title}</h4>

                  <p className="stext-117 cl6 p-b-26">
                    {product.first_content}
                  </p>

                  <p className="stext-117 cl6 p-b-26">
                    {product.second_content}
                  </p>
                </div>
              </div>
            </div>

            <div className="col-md-4 col-lg-3 p-b-80">
              <div className="side-menu">
                {relatedBlogsData.map((blog) => {
                  return <RelatedBlogs {...blog} />;
                })}
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default BlogDetail;

export const getStaticPaths: GetStaticPaths = async () => {
  const featuredBlogsRes = await fetch("http://localhost:5001/blogs");
  const featuredBlogsData: FeaturedBlogsType[] = await featuredBlogsRes.json();

  const paths = featuredBlogsData.map((product) => {
    return {
      params: {
        id: product.id,
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
};
export const getStaticProps: GetStaticProps = async ({ params }) => {
  const allFeaturedBlogsRes = await fetch("http://localhost:5001/blogs");
  const allFeaturedBlogsData = await allFeaturedBlogsRes.json();

  let product: FeaturedBlogsType | undefined = undefined;

  if (params?.id) {
    const featuredBlogRes = await fetch(
      `http://localhost:5001/blogs/${params.id}`
    );
    product = await featuredBlogRes.json();
  }

  return {
    props: {
      product,
      allFeaturedBlogsData,
    },
  };
};
